name: Deploy to Xserver

# mainブランチにプッシュされた時に実行する
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSPHRASE }} # このActionでは password という項目名でパスフレーズを受け取ります
          port: ${{ secrets.SSH_PORT }}
          local_path: './*' # ローカルの全ファイルを対象にする
          remote_path: '/home/hide566566/cocomachi-marche.com/public_html/2026_takanedai_LINE/'
          sftp_only: true # 接続をSFTPに限定する
